jobs:
- job: DeployWebsite
  steps:
  - task: azureResourceGroupDeployment@2
    displayName: 'Deploy website'
    inputs:
      azureSubscription: 'MSDN Platforms Subscription'
      resourceGroupName: 'AzureWebsite1'
      location: 'West US 2'
      templateLocation: 'Linked artifact'
      csmFile: 'AzureWebsite1csm.json'
      csmParametersFile: 'AzureWebsite1param.json'
      deploymentMode: 'Incremental'

